#!/usr/bin/env bash
# Task 1
apt-get -y update
apt-get -y install nginx
chown -R "$USER":"$USER" /var/www/html
echo "Holberton School" > /var/www/html/index.html
ufw allow 'Nginx HTTP'
service nginx start
