#!/usr/bin/env bash
# Task 1
apt-get update
apt-get -y install nginx
chown -R "$USER":"$USER" /var/www/html/index.nginx-debian.html
chmod -R 755 /var/www
echo "Holberton School" > /var/www/html/index.nginx-debian.html
ufw allow 'Nginx HTTP'
service nginx restart
