#!/usr/bin/env bash
# Task 3
apt-get update
apt-get -y install nginx
chown -R "$USER":"$USER" /var/www/html/index.nginx-debian.html
chmod -R 755 /var/www
echo "Holberton School" > /var/www/html/index.nginx-debian.html
f=$(printf %s "location /redirect_me {return 301 https://www.youtube.com/watch?v=QH2-TGUlwu4;}")
sed -i  "48i $f" /etc/nginx/sites-available/default
ufw allow 'Nginx HTTP'
service nginx restart
