#!/usr/bin/env bash
# Task 0
sudo add-apt-repository -y ppa:vbernat/haproxy-1.8
sudo apt-get -y update
sudo apt-get -y install haproxy=1.8.\*
sudo service haproxy start
sed -i "$ a ENABLED=1" /etc/default/haproxy
sed -i "$ a frontend http\n        bind *:80\n        default_backend webservers\nbackend webservers\n        server 1939-web-01 35.231.99.203:80 check\n        server 1939-web-02 35.196.75.2:80 check\n" /etc/haproxy/haproxy.cfg
sudo service haproxy restart
