#!/usr/bin/env bash
#Repeat i 20 times with a twist
i="1"
while [ $i -lt 21 ]
do
if [ $i == 4 ] 
then
echo "bad luck"
elif [ $i == 9 ] 
then
echo "good luck"
elif [ $i == 17 ] 
then
echo "good luck"
else
echo "$i"
fi
i=$((i + 1))
done