#!/usr/bin/env bash
#Repeat i 20 times with a twist
i="1"
while [ $i -lt 21 ]
do
case $i in
4)
echo "bad luck from China"
;;
9)
echo "bad luck from Japan"
;;
17)
echo "bad luck from Italy!"
;;
*)
echo "$i"
;;
esac
i=$((i + 1))
done