#!/usr/bin/env bash
# Task 1
sudo chown -R nginx:nginx /etc/nginx/nginx.conf
sudo chmod -R 644 /etc/nginx/nginx.conf
sudo sed -i 's/80/8080/' /etc/nginx/sites-enabled/default
sudo -u nginx service nginx start
